name: HuntailHunters
main: com.Fennek.huntailHunters.HuntailHunters
version: 1.1.8
description: A "One In The Quiver" event plugin for Minecraft servers.
author: FennekFoxy
commands:
  huntailhunters:
    description: Main command for managing HuntailHunters arenas and games.
    aliases: [hh]
    usage: /<command> <args>
    permission: huntailhunters.use
    subcommands:
      join:
        description: Join the current game.
        usage: /huntailhunters join
        permission: huntailhunters.join
      create:
        description: Create an arena with specified coordinates and name.
        usage: /huntailhunters create <x1> <y1> <z1> <x2> <y2> <z2> <name>
        permission: huntailhunters.create
      start:
        description: Start a game in the specified arena with or without power-ups.
        usage: /huntailhunters start <arena> <true/false>
        permission: huntailhunters.start
      stop:
        description: Stop the current game in the specified arena.
        usage: /huntailhunters stop <arena>
        permission: huntailhunters.stop
      delete:
        description: Delete the specified arena.
        usage: /huntailhunters delete <arena>
        permission: huntailhunters.delete
      confirmdelete:
        description: Confirm the deletion of an arena.
        usage: /huntailhunters confirmdelete <arena>
        permission: huntailhunters.delete
      declinedelete:
        description: Cancel the deletion of an arena.
        usage: /huntailhunters declinedelete
        permission: huntailhunters.delete
      stats:
        description: Show statistics for the specified player, or yourself if not specified.
        usage: /huntailhunters stats <IGN>
        permission: huntailhunters.stats
      round:
        description: Start a round in the specified arena with a given round number and power-ups.
        usage: /huntailhunters round <arena> <round_number> start <true/false>
        permission: huntailhunters.start
permissions:
  huntailhunters.use:
    description: Allows the player to use the HuntailHunters commands.
    default: true
  huntailhunters.join:
    description: Allows the player to join the HuntailHunters game.
    default: true
  huntailhunters.create:
    description: Allows the player to create a new arena.
    default: op
  huntailhunters.spawn:
    description: Allows the player to change spawn in an arena.
    default: op
  huntailhunters.powerup:
    description: Allows the player to add powerup spawns to an arena.
    default: op
  huntailhunters.start:
    description: Allows the player to start a game in an arena.
    default: op
  huntailhunters.stop:
    description: Allows the player to stop an ongoing game.
    default: op
  huntailhunters.delete:
    description: Allows the player to delete an existing arena.
    default: op
  huntailhunters.stats:
    description: Allows the player to view player statistics.
    default: true
